projects/djangovenv/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
]

projects/djangovenv/pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
]

projects/djangovenv/pybo/models.py
from django.db import models

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Answer(models.Model) :
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

projects/djangovenv/pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Question
from django.utils import timezone


def index(request):
    """pybo 목록 출력"""
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    """pybo 내용 출력"""
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


def answer_create(request, question_id):
    """pybo 답변 등록"""

    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    return redirect('pybo:detail', question_id=question.id)
#    question = get_object_or_404(Question, pk=question_id)
#   answer = Answer(question=question, content=request.POST.get('content'), create_date=timezone.now())
#   answer.save()

projects/djangovenv/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello pybo!</title>
</head>
<body>
<!-- base template에 삽입될 내용 시작 -->
{% block content %}
{% endblock %}
<!-- base template에 삽입될 내용 끝 -->
</body>
</html>

projects/djangovenv/templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">
        {{  question.subject  }}
    </h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{  question.content  }}
            </div>
        </div>
    </div>
</div>
<h5 class="border-bottom my-3 py-2">
    This Question has got the {{  question.answer_set.count  }} answer(s).
</h5>
{% for answer in question.answer_set.all %}
<div class="card my-3">
    <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">
            {{  answer.content  }}
        </div>
        <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2">
                {{  answer.create_date  }}
            </div>
    </div>
</div>
{%  endfor %}
<form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
    {% csrf_token %}
    <div class="form-group">
        <textarea name="content" id="content" class="form-control" rows="10"></textarea>
    </div>
    <input type="submit" value="Submit Answer" class="btn btn-primary">
 </form>
</div>
{% endblock %}

projects/djangovenv/templates/pybo/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
  <table class="table">
    <thead>
    <tr class="thead-dark">
      <th>number</th>
      <th>title</th>
      <th>create time</th>
    </tr>
    </thead>
    <tbody>
    {% if question_list %}
    {% for question in question_list %}
    <tr>
      <td>
        {{  forloop.counter  }}
      </td>
      <td>
        <a href="{% url 'pybo:detail' question.id %}">
          {{  question.subject  }}
        </a>
      </td>
      <td>
        {{ question.create_date  }}
      </td>
    </tr>
    {% endfor %}
    {% else %}
    <tr>
      <td colspan="3">No Question</td>
    </tr>
    {% endif %}
    </tbody>
  </table>
</div>
{% endblock %}